package world.cepi.mob.meta

import kotlinx.serialization.modules.SerializersModule
import kotlin.reflect.KClass

public val list: Array<KClass<out Any>> = arrayOf(
    MetaFireworkRocket::class,
    MetaFallingBlock::class,
    MetaAbstractArrow::class,
    MetaBoat::class,
    MetaExperienceOrb::class,
    MetaPainting::class,
    MetaItemFrame::class,
    MetaLivingEntity::class,
    MetaFishingHook::class,
    MetaWitherSkull::class,
    MetaPrimedTnt::class,
    MetaAbstractMinecart::class,
    MetaEndCrystal::class,
    MetaAreaEffectCloud::class,
    MetaThrownTrident::class,
    MetaArrow::class,
    MetaEyeOfEnder::class,
    MetaItemEntity::class,
    MetaSnowball::class,
    MetaFireball::class,
    MetaThrownExperienceBottle::class,
    MetaThrownPotion::class,
    MetaThrownEnderPearl::class,
    MetaThrownEgg::class,
    MetaSmallFireball::class,
    MetaArmorStand::class,
    MetaMob::class,
    MetaPlayer::class,
    MetaCommandBlockMinecart::class,
    MetaFurnaceMinecart::class,
    MetaSlime::class,
    MetaEnderDragon::class,
    MetaAgeableMob::class,
    MetaGhast::class,
    MetaPhantom::class,
    MetaBat::class,
    MetaAbstractVillager::class,
    MetaVex::class,
    MetaGuardian::class,
    MetaWither::class,
    MetaSpider::class,
    MetaCreeper::class,
    MetaZoglin::class,
    MetaBasePiglin::class,
    MetaRaider::class,
    MetaZombie::class,
    MetaEnderman::class,
    MetaBlaze::class,
    MetaIronGolem::class,
    MetaSnowGolem::class,
    MetaShulker::class,
    MetaAbstractFish::class,
    MetaDolphin::class,
    MetaAxolotl::class,
    MetaHoglin::class,
    MetaBee::class,
    MetaPolarBear::class,
    MetaPig::class,
    MetaAbstractHorse::class,
    MetaOcelot::class,
    MetaGoat::class,
    MetaTameableAnimal::class,
    MetaFox::class,
    MetaPanda::class,
    MetaRabbit::class,
    MetaStrider::class,
    MetaTurtle::class,
    MetaSheep::class,
    MetaPiglin::class,
    MetaWitch::class,
    MetaZombieVillager::class,
    MetaPufferfish::class,
    MetaMooshroom::class,
    MetaChestedHorse::class,
    MetaCat::class,
    MetaParrot::class,
    MetaWolf::class,
    MetaSpellcasterIllager::class,
    MetaLlama::class
    )

public val module: SerializersModule = SerializersModule { }
